import 'package:freezed_annotation/freezed_annotation.dart';

part 'diet_plan.freezed.dart';
part 'diet_plan.g.dart';

/// Represents a diet plan with specific nutritional goals and restrictions
@freezed
class DietPlan with _$DietPlan {
  const factory DietPlan({
    required String id,
    required String userId,
    required String name,
    required DateTime createdAt,
    DateTime? lastModifiedAt,
    required DateTime startDate,
    DateTime? endDate,
    required NutritionalGoals dailyGoals,
    @Default([]) List<DietaryRestriction> restrictions,
    @Default([]) List<String> preferredFoods,
    @Default([]) List<String> dislikedFoods,
    String? description,
    @Default(false) bool isActive,
    @Default(DietPlanSource.user) DietPlanSource source,
    @Default({}) Map<String, dynamic> metadata,
  }) = _DietPlan;

  factory DietPlan.fromJson(Map<String, dynamic> json) =>
      _$DietPlanFromJson(json);
}

/// Represents daily nutritional goals for a diet plan
@freezed
class NutritionalGoals with _$NutritionalGoals {
  const factory NutritionalGoals({
    required double calories,
    required double protein, // in grams
    required double carbs, // in grams
    required double fat, // in grams
    double? fiber, // in grams
    double? sugar, // in grams
    double? sodium, // in mg
    @Default({})
    Map<String, double>
    micronutrients, // Map of micronutrient name to target amount
  }) = _NutritionalGoals;

  factory NutritionalGoals.fromJson(Map<String, dynamic> json) =>
      _$NutritionalGoalsFromJson(json);
}

/// Represents a dietary restriction for a diet plan
@freezed
class DietaryRestriction with _$DietaryRestriction {
  const factory DietaryRestriction({
    required String id,
    required String name,
    required RestrictionType type,
    String? description,
    @Default([]) List<String> restrictedFoods,
    @Default([]) List<String> restrictedCategories,
  }) = _DietaryRestriction;

  factory DietaryRestriction.fromJson(Map<String, dynamic> json) =>
      _$DietaryRestrictionFromJson(json);
}

/// Type of dietary restriction
enum RestrictionType {
  allergy, // Food allergy (severe)
  intolerance, // Food intolerance (moderate)
  avoidance, // Personal choice to avoid
  religious, // Religious restriction
  medical, // Medical restriction
  lifestyle, // Lifestyle choice (e.g., vegan, vegetarian)
}

/// Source of a diet plan
enum DietPlanSource {
  user, // Created by the user
  nutritionist, // Created by a nutritionist
  ai, // Generated by AI
  template, // Created from a template
}
