# Build configuration for code generation
targets:
  $default:
    builders:
      injectable_generator:injectable:
        options:
          auto_register: true
          class_name_pattern: ".*Repository$|.*Service$|.*Client$"
      
      freezed:freezed:
        enabled: true
        
      json_serializable:json_serializable:
        options:
          any_map: false
          checked: false
          create_factory: true
          create_to_json: true
          disallow_unrecognized_keys: false
          explicit_to_json: false
          field_rename: none
          include_if_null: true
          
      riverpod_generator:riverpod_generator:
        enabled: true
