// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpUQUbaKcmVVOlYA2KEGe3-XmeJ5TORvg',
    appId: '1:115156539680:web:432b5f46e6cf019a1f9f45',
    messagingSenderId: '115156539680',
    projectId: 'nutrivision-cae68',
    authDomain: 'nutrivision-cae68.firebaseapp.com',
    storageBucket: 'nutrivision-cae68.firebasestorage.app',
    measurementId: 'G-NC023EGD7E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMQpkaXzrYtzocNU8WZE7WEzFoOikof3A',
    appId: '1:115156539680:android:c5ada66de89205341f9f45',
    messagingSenderId: '115156539680',
    projectId: 'nutrivision-cae68',
    storageBucket: 'nutrivision-cae68.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAS426Ya5X3w9bzAwzUGi5VFBR7YghvmMw',
    appId: '1:115156539680:ios:b731050a1eda881d1f9f45',
    messagingSenderId: '115156539680',
    projectId: 'nutrivision-cae68',
    storageBucket: 'nutrivision-cae68.firebasestorage.app',
    iosBundleId: 'com.decent.dev.nutrivision',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAS426Ya5X3w9bzAwzUGi5VFBR7YghvmMw',
    appId: '1:115156539680:ios:c9294fc85a01a14c1f9f45',
    messagingSenderId: '115156539680',
    projectId: 'nutrivision-cae68',
    storageBucket: 'nutrivision-cae68.firebasestorage.app',
    iosBundleId: 'com.example.nutrivision',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpUQUbaKcmVVOlYA2KEGe3-XmeJ5TORvg',
    appId: '1:115156539680:web:83d9baf15a2198f51f9f45',
    messagingSenderId: '115156539680',
    projectId: 'nutrivision-cae68',
    authDomain: 'nutrivision-cae68.firebaseapp.com',
    storageBucket: 'nutrivision-cae68.firebasestorage.app',
    measurementId: 'G-F85XQYTFEM',
  );
}
